name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6

      - name: Install calibre
        run: |
          sudo apt update
          sudo apt install libegl1 libopengl0 libxcb-cursor0
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Compile translation file
        run: calibre-debug -c "from calibre.translations.msgfmt import main; main()" translations/*.po

      - name: Build plugin
        run: zip -r worddumb-${{ github.ref_name }}.zip * -x@exclude.lst

      - name: Create relase
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TELEMETRY: false
        run: gh release create ${{ github.ref_name }} worddumb-${{ github.ref_name }}.zip
